export const SURVEY_FIELDS = {
  K2: [
    { "backend": "sy_snum", "csv": "Number of Stars", "type": "int" },
    { "backend": "sy_pnum", "csv": "Number of Planets", "type": "int" },
    { "backend": "soltype", "csv": "Solution Type", "type": "string" },
    { "backend": "pl_orbper", "csv": "Orbital Period [days]", "type": "float" },
    { "backend": "pl_orbpererr1", "csv": "Orbital Period [positive (+ve) Error]", "type": "float" },
    { "backend": "pl_orbpererr2", "csv": "Orbital Period [negative (-ve) Error]", "type": "float" },
    { "backend": "pl_rade", "csv": "Planet Radius [Earth radii]", "type": "float" },
    { "backend": "pl_radeerr1", "csv": "Planet Radius [positive (+ve) Error]", "type": "float" },
    { "backend": "pl_radeerr2", "csv": "Planet Radius [negative (-ve) Error]", "type": "float" },
    { "backend": "pl_radj", "csv": "Planet Radius [Jupiter radii]", "type": "float" },
    { "backend": "pl_radjerr1", "csv": "Planet Radius [positive (+ve) Error]", "type": "float" },
    { "backend": "pl_radjerr2", "csv": "Planet Radius [negative (-ve) Error]", "type": "float" },
    { "backend": "ttv_flag", "csv": "Data show Transit Timing Variations", "type": "int" },
    { "backend": "st_teff", "csv": "Stellar Effective Temperature [K]", "type": "float" },
    { "backend": "st_tefferr1", "csv": "Stellar Effective Temperature [positive (+ve) Error]", "type": "float" },
    { "backend": "st_tefferr2", "csv": "Stellar Effective Temperature [negative (-ve) Error]", "type": "float" },
    { "backend": "st_rad", "csv": "Stellar Radius [Solar radii]", "type": "float" },
    { "backend": "st_raderr1", "csv": "Stellar Radius [positive (+ve) Error]", "type": "float" },
    { "backend": "st_raderr2", "csv": "Stellar Radius [negative (-ve) Error]", "type": "float" },
    { "backend": "ra", "csv": "RA [decimal degrees]", "type": "float" },
    { "backend": "dec", "csv": "Dec [decimal degrees]", "type": "float" },
    { "backend": "sy_dist", "csv": "Distance [pc]", "type": "float" },
    { "backend": "sy_disterr1", "csv": "Distance [pc] [positive (+ve) Error]", "type": "float" },
    { "backend": "sy_disterr2", "csv": "Distance [pc] [negative (-ve) Error]", "type": "float" },
    { "backend": "sy_vmag", "csv": "V-(Johnson) [magnitude]", "type": "float" },
    { "backend": "sy_kmag", "csv": "Ks-band (2MASS) [magnitude]", "type": "float" },
    { "backend": "sy_kmagerr1", "csv": "Ks-band (2MASS) [positive (+ve) Error]", "type": "float" },
    { "backend": "sy_kmagerr2", "csv": "Ks-band (2MASS) [negative (-ve) Error]", "type": "float" },
    { "backend": "sy_gaiamag", "csv": "Gaia Magnitude", "type": "float" },
    { "backend": "sy_gaiamagerr1", "csv": "Gaia Magnitude [positive (+ve) Error]", "type": "float" },
    { "backend": "sy_gaiamagerr2", "csv": "Gaia Magnitude [negative (-ve) Error]", "type": "float" } 
  ],
   KOI: [
    { "backend": "koi_pdisposition", "csv": "Disposition Using Kepler Data", "type": "string" },
    { "backend": "koi score", "csv": "Disposition Score", "type": "float" },
    { "backend": "koi_fpflag_ss", "csv": "Stellar Eclipse False Positive Flag", "type": "int" },
    { "backend": "koi_fpflag_co", "csv": "Centroid Offset False Positive Flag", "type": "int" },
    { "backend": "koi_fpflag_ec", "csv": "Ephemeris Match Indicates Contamination False Positive Flag", "type": "int" },
    { "backend": "koi_period", "csv": "Orbital Period (days)", "type": "float" },
    { "backend": "koi_period_err1", "csv": "Orbital Period [positive (+ve) Error]", "type": "float" },
    { "backend": "koi_period_err2", "csv": "Orbital Period [negative (-ve) Error]", "type": "float" },
    { "backend": "koi_time0bk", "csv": "Transit Epoch (BKJD)", "type": "float" },
    { "backend": "koi_time0bk_err1", "csv": "Transit Epoch [positive (+ve) Error]", "type": "float" },
    { "backend": "koi_time0bk_err2", "csv": "Transit Epoch [negative (-ve) Error]", "type": "float" },
    { "backend": "koi_impact", "csv": "Impact Parameter", "type": "float" },
    { "backend": "koi_duration", "csv": "Transit Duration (hours)", "type": "float" },
    { "backend": "koi_duration_err1", "csv": "Transit Duration [positive (+ve) Error]", "type": "float" },
    { "backend": "koi_duration_err2", "csv": "Transit Duration [negative (-ve) Error]", "type": "float" },
    { "backend": "koi_depth", "csv": "Transit Depth (parts per million)", "type": "float" },
    { "backend": "koi_depth_err1", "csv": "Transit Depth [positive (+ve) Error]", "type": "float" },
    { "backend": "koi_depth_err2", "csv": "Transit Depth [negative (-ve) Error]", "type": "float" },
    { "backend": "koi_prad", "csv": "Planetary Radius (Earth radii)", "type": "float" },
    { "backend": "koi_prad_err1", "csv": "Planetary Radius [positive (+ve) Error]", "type": "float" },
    { "backend": "koi_prad_err2", "csv": "Planetary Radius [negative (-ve) Error]", "type": "float" },
    { "backend": "koi_teq", "csv": "Equilibrium Temperature (Kelvin)", "type": "float" },
    { "backend": "koi_insol", "csv": "Insolation Flux [Earth flux]", "type": "float" },
    { "backend": "koi_insol_err1", "csv": "Insolation Flux [positive (+ve) Error]", "type": "float" },
    { "backend": "koi_insol_err2", "csv": "Insolation Flux [negative (-ve) Error]", "type": "float" },
    { "backend": "koi model snr", "csv": "Transit Signal-to-Noise", "type": "float" },
    { "backend": "koi_tce_plnt_num", "csv": "TCE Planet Number", "type": "int" },
    { "backend": "koi tce delivname", "csv": "TCE Delivery Name", "type": "String" },
    { "backend": "koi_steff", "csv": "Stellar Effective Temperature (Kelvin)", "type": "float" },
    { "backend": "koi_steff_err1", "csv": "Stellar Effective Temperature [positive (+ve) Error]", "type": "float" },
    { "backend": "koi_steff_err2", "csv": "Stellar Effective Temperature [negative (-ve) Error]", "type": "float" },
    { "backend": "koi_slogg", "csv": "Stellar Surface Gravity (log10(cm s-2)", "type": "float" },
    { "backend": "koi_slogg_err1", "csv": "Stellar Surface Gravity [positive (+ve) Error]", "type": "float" },
    { "backend": "koi_slogg_err2", "csv": "Stellar Surface Gravity [negative (-ve) Error]", "type": "float" },
    { "backend": "koi_srad", "csv": "Stellar Radius (solar radii)", "type": "float" },
    { "backend": "koi_srad_err1", "csv": "Stellar Radius (solar radii) [positive (+ve) Error]", "type": "float" },
    { "backend": "koi_srad_err2", "csv": "Stellar Radius (solar radii) [negative (-ve) Error]", "type": "float" },
    { "backend": "ra", "csv": "RA (decimal degrees)", "type": "float" },
    { "backend": "dec", "csv": "Dec (decimal degrees)", "type": "float" },
    { "backend": "koi_kepmag", "csv": "Kepler-band (magnitude)", "type": "float" }  
  ],
  TESS: [
   { "backend": "ra", "csv": "RA [decimal degrees]", "type": "float" },
    { "backend": "dec", "csv": "Dec [decimal degrees]", "type": "float" },
    { "backend": "st_pmra", "csv": "PMRA [mas/yr]", "type": "float" },
    { "backend": "st_pmraerr1", "csv": "PMRA [positive (+ve) Error]", "type": "float" },
    { "backend": "st_pmraerr2", "csv": "PMRA [negative (-ve) Error]", "type": "float" },
    { "backend": "st_pmdec", "csv": "PMDec [mas/yr]", "type": "float" },
    { "backend": "st_pmdecerr1", "csv": "PMDec [positive (+ve) Error]", "type": "float" },
    { "backend": "st_pmdecerr2", "csv": "PMDec [negative (-ve) Error]", "type": "float" },
    { "backend": "pl_tranmid", "csv": "Planet Transit Midpoint [BJD]", "type": "float" },
    { "backend": "pl_tranmiderr1", "csv": "Planet Transit Midpoint [positive (+ve) Error]", "type": "float" },
    { "backend": "pl_tranmiderr2", "csv": "Planet Transit Midpoint [negative (-ve) Error]", "type": "float" },
    { "backend": "pl_orbper", "csv": "Planet Orbital Period [days]", "type": "float" },
    { "backend": "pl_orbpererr1", "csv": "Planet Orbital Period [positive (+ve) Error]", "type": "float" },
    { "backend": "pl_orbpererr2", "csv": "Planet Orbital Period [negative (-ve) Error]", "type": "float" },
    { "backend": "pl_trandurh", "csv": "Planet Transit Duration [hours]", "type": "float" },
    { "backend": "pl_trandurherr1", "csv": "Planet Transit Duration [positive (+ve) Error]", "type": "float" },
    { "backend": "pl_trandurherr2", "csv": "Planet Transit Duration [negative (-ve) Error]", "type": "float" },
    { "backend": "pl_trandep", "csv": "Planet Transit Depth [ppm]", "type": "float" },
    { "backend": "pl_trandeperr1", "csv": "Planet Transit Depth [positive (+ve) Error]", "type": "float" },
    { "backend": "pl_trandeperr2", "csv": "Planet Transit Depth [negative (-ve) Error]", "type": "float" },
    { "backend": "pl_rade", "csv": "Planet Radius [R_Earth]", "type": "float" },
    { "backend": "pl_radeerr1", "csv": "Planet Radius [R_Earth] [positive (+ve) Error]", "type": "float" },
    { "backend": "pl_radeerr2", "csv": "Planet Radius [R_Earth] [negative (-ve) Error]", "type": "float" },
    { "backend": "pl_insol", "csv": "Planet Insolation [Earth flux]", "type": "float" },
    { "backend": "pl_eqt", "csv": "Planet Equilibrium Temperature [K]", "type": "float" },
    { "backend": "st_tmag", "csv": "TESS Magnitude", "type": "float" },
    { "backend": "st_tmagerr1", "csv": "TESS Magnitude [positive (+ve) Error]", "type": "float" },
    { "backend": "st_tmagerr2", "csv": "TESS Magnitude [negative (-ve) Error]", "type": "float" },
    { "backend": "st dist", "csv": "Stellar Distance [pc]", "type": "float" },
    { "backend": "st disterr1", "csv": "Stellar Distance [positive (+ve) Error]", "type": "float" },
    { "backend": "st_disterr2", "csv": "Stellar Distance [negative (-ve) Error]", "type": "float" },
    { "backend": "st_teff", "csv": "Stellar Effective Temperature [K]", "type": "float" },
    { "backend": "st_tefferr1", "csv": "Stellar Effective Temperature [positive (+ve) Error]", "type": "float" },
    { "backend": "st_tefferr2", "csv": "Stellar Effective Temperature [negative (-ve) Error]", "type": "float" },
    { "backend": "st_logg", "csv": "Stellar log(g) [cm/s**2]", "type": "float" },
    { "backend": "st_loggerr1", "csv": "Stellar log(g) [positive (+ve) Error]", "type": "float" },
    { "backend": "st_loggerr2", "csv": "Stellar log(g) [negative (-ve) Error]", "type": "float" },
    { "backend": "st rad", "csv": "Stellar Radius [R_Sun]", "type": "float" },
    { "backend": "st_raderr1", "csv": "Stellar Radius [positive (+ve) Error]", "type": "float" },
    { "backend": "st_raderr2", "csv": "Stellar Radius [negative (-ve) Error]", "type": "float" }
  ],
};